version: '3'

services:
  db:
    image: mysql:5.6.47
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/mysql/data  

  app:
    tty: true 
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/projects/report_app
    ports:
      - "3000:3000"
    depends_on:
       - db